// Noctifuge All Rights Reserved 

#pragma once

#include "NativeGameplayTags.h"

namespace  LOSGameplayTags
{
	/**Input Tags**/
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipSword)
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipSword)

	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Sword)
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Sword)

	/**Player Tags**/
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Sword)
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Sword)
	
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Sword)
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Sword)

	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword)
	
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Sword)
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Sword)

	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Combo_ChainWindow)

	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher)
	
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light)
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy)

	/**Enemy Tags**/
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee)
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged)
	
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon)

	/**Shared Tags**/
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact)
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit)
	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact)

	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage)

	LANDOFSOULS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
}
